#!/bin/busybox sh

recovery()
{
	echo "Some init command failed."
	echo "Dropping to a shell."
	sleep 5
	exec sh
}

mount -t proc none /proc || recovery 
mount -t sysfs none /sys || recovery

mount -o ro /dev/sda1 /mnt/root || recovery 
umount /proc || recovery 
umount /sys || recovery

exit 0
