#!/bin/busybox sh

recovery()
{
	/bin/echo "Some init command failed."
	/bin/echo "Dropping to a shell."
}

/bin/mount -t proc none /proc || recovery 
/bin/mount -t sysfs none /sys || recovery

/bin/sh
#/bin/mount -o ro /dev/sda1 /mnt/root || recovery 

/bin/umount /proc || recovery 
/bin/umount /sys || recovery

exit 0
